language: node_js

node_js:
  - 'stable'

dist: xenial
addons:
  apt:
    packages:
      - libsecret-1-dev
sudo: required
services:
  - xvfb

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;

install:
  - npm install -g vsce
  - npm install

script:
  - npm run lint
  - npm run test
  - vsce package

notifications:
  email:
    on_success: never
    on_failure: always